5. 모든 정점사이에 간선이 존재한다면, 인접행렬을 사용할 때 모든A[i][j]를 1로 채울 수 있으니 편리하다.  

6. 인접 리스트를 사용한다. 간선이 적다면 리스트로 표현되는 것이 한눈에 들어올 수 있고 메모리 소비가 적어질 수 있다.

8. 깊이 우선 탐색인 1에서 for loop를 하면 1의 adj인 x=2가 호출된다 2에서 3, 5, 6, 4순으로 탐색한다. 1에서 x=4로 갈 때는 이미 방문한 상태이므로 DFS(x)는 한번 호출된다.

12.

(1) 프림 알고리즘에서의 시작 정점을 "안"부터 한다면 인접한 정점중 가중치가 제일 작은 4를 선택한다. 그다음 2,1,3으로 간 뒤 가중치가 5인 정점으로 확장한다. 여기서 아랫부분의 7,8에 간선을 이으면 사이클이 생기므로 가중치가 9인 것을 선택한다. 바로 이어진 가중치 8을 선택하면 n-1=7을 만족하는 치소 신장 트리를 구할 수 있다. 

(2) 크루스칼 알고리즘은 가중치가 사이클을 이루지 않는 최소 비용 간선을 선택한다. 먼저 오름차순으로 정렬하고 가장 가중치가 작은 간선 1을 뽑는다 그 다음은 2,3,4,5까지 한 뒤 7을 삽입하면 사이클이 생기므로 8,9로 넘어간다. 그러면 간선의 수가 n-1=7개이고 모든 정점을 방문한다.

16. 
````
Topological Sort with STACK: 
    Create STACK 
    Create visited <- false 
    for each vertex v  
        if(!visited[v]) 
            DFS(v, visited, STACK) 
    while(!STACK.empty) 
        STACK.pop 
 
DFS(v, visited, STACK) 
    visited[v] <- true 
    for i in Adj[v] 
        if(!visited[i]) 
            DFS 
    STACK.push(v)
    ````

먼저 a를 시작으로 두고 d e f g h의 순서를 구하면 d→e→f→g→h와 d→e→f→h→g로 총 2개가 가능하다
그러면 b의 삽입 위치에 따라 c가 결정된다. b를 d앞에 두면 c는 6곳 올 수 있고, b를 e앞에 두면 c는 5곳, 점점 c의 개수가 1로 줄어들어서 c의 모든 삽입가능 위치를 합하면 21가지 나오고 앞에 defgh의 순서 2가지를 곱하면 총 42가지가 나온다.

17.

| S | 노드 | d |
|---|---|---|
| Q | Q | 0 |
| E | A | 10 → 9 |
| C | B | ∞ → 15 |
| A | C | 7 |
| F | D | ∞ → 19 |
| B | E | 4 |
| D | F | ∞ → 12 |
| G | G | ∞ → 24 → 23 |

18. S, A, B의 정점이 있다고 가정하고 S->A = 5, S->B = 2, A->B = -10일 때 S를 확정하고 d가 가장 작은 값인 B를 확정한다. 하지만 음의 가중치가 있기 떄문에 실제 최소값은 -5가 나오지만 B는 이미 확정되어 있기 떄문에 갱신이 불가하여 다익스트라 알고리즘이 작동하지 않는다. 

22. 벨만포드는 음의 가중치가 있어도 작동하지만, 그래프 안에 가중치의 합이 음수인 사이클이 있으면 그 사이클은 돌수록 거리가 무한히 감소하기 때문에 최단거리가 측정되지 않아서 답을 구할 수 없다.

5. 12 70 30 20 55 25

(1)선택정렬 
[12 25 30 20 55 | 70]
[12 25 30 20 | 55 | 70]
[12 25 20 | 30 | 55 | 70]
[12 20| 25 | 30 | 55 | 70]
[12| 20| 25 | 30 | 55 | 70]

(2)버블정렬
Pass1
[12 70 30 20 55 25]
[12 30 70 20 55 25]
[12 30 20 70 55 25]
[12 30 20 55 70 25]
[12 30 20 55 25 70]
Pass2
[12 20 30 55 25 70]
[12 20 30 25 55 70]
Pass3
[12 20 25 30 55 70]
Pass4
변경이 없으므로 정렬 완료
[12 20 25 30 55 70]

(3)삽입정렬
[12 70 30 20 55 25]
[12 30 70 20 55 25]
[12 20 30 70 55 25]
[12 20 30 55 70 25]
[12 20 25 30 55 70]

6. [12 70 30 20 55 25 40 50] 

(1)병합정렬
먼저 분할을 한다
[12 70 30 20] [55 25 40 50] 
[12 70] [30 20] [55 25] [40 50] 
[12] [70] [30] [20] [55] [25] [40] [50] 
순서대로 병합하면
[12 70] [20 30] [25 55] [40 50] 
[12 20 30 70] [25 40 50 55]
[12 20 25 30 40 50 55 70] 이 나온다

(2)힙정렬
[12 70 30 20 55 25 40 50]
0 1 2 3 4 5 6 7을 인덱스로 삼고 최대힙을 구성하면
[70 55 40 50 12 25 30 20]이 나온다. 이제 최댓값을 끝으로 보내며 정렬을 한다
[20 55 40 50 12 25 30 |70]
Heapify를 하면 [55 50 40 20 12 25 30 |70]이고 
[30 50 40 20 12 25 | 55 |70]
Heapify를 하면  [50 30 40 20 12 25 | 55 |70]이고
[25 30 40 20 12 |50 | 55 |70]
Heapify를 하면 [40 30 25 20 12 |50 | 55 |70]
[12 30 25 20 | 40 |50 | 55 |70]
Heapify를 하면 [ 30 20 25 12| 40 |50 | 55 |70]
[ 12 20 25 |30| 40 |50 | 55 |70]
Heapify를 하면 [ 25 20 12 |30| 40 |50 | 55 |70]
[12 20 |25|30| 40 |50 | 55 |70]에서
결국 [12 20 25 30 40 50 55 70]으로 정렬된다

(3)퀵정렬
[12 70 30 20 55 25 40 50] 에서 40을 피벗으로 설정하면 
[12 30 20 25 |40| 70 55 50]이고 왼쪽과 오른쪽을 정렬하면
[12 20 25 30 40 50 55 70]이 된다.